### ISSUE TITLE
We Dont Want 1999!!

### ISSUE THREAD

**Issue by ImLoadingUuU** [MyOwnFreeHostCommunity/Mofhy#3]
We Dont Want 1999!
**_if  assets.mofhy.tk DOWN!ALL MOFHY COMMUNITYY EDITION USER WEBSITE TURN INTO 1999!_**
               

 _-  FatGrizzly#5803_

**Comment by jaikt** [comment]
It wont go down, it is hosted on google cloud cdn and aws cloudront. If one goes down, there is a backup :)

**Comment by Wallvon** [comment]
Well, there are numerous other issues that come with this:

- Freenom likes to point domains to various NSFW sites when you get even a little bit of traffic, and you'll have to pay to get your domain back.
- You (or whoever pays for the Google Cloud and AWS instance) could stop paying for the CDN instances due to various reasons and the files would also be gone.
- If you ever decide to stop working on MOFHY you will still have to keep up the CDN for whoever uses this.

I would suggest just using local files, but if you really want to use a CDN since it is so much better or whatever, just use https://www.jsdelivr.com/ and point it to the files in this repo.

**Comment by jaikt** [comment]
Ohk, looks like local assets are preferred.
